### PR TITLE
Fixed 'outputComplex' issue

### PR DESCRIPTION
**Pull request by AleksandrTulenkov**
Already described issue, 'output Complex' deprecated

### CODE REVIEW

**Comment by BuddyVolly** [comment]
Hi Aleksandr, 

there are lots of changes, because of aded spaces, so I am not finding the issue. Can you resend Can you resend the PR without those spaces, so I can just see what actually went wrong?
In addition, which SNAP version do you use? Problems with xml files are usually tied to specifics of SNAP versions. OST at the moment uses Snap version 8

Thanks,
Andreas

**Comment by alexisahedo** [comment]
Hello everyone. 
Excuse me, I'm experiencing this same issue and I'm wondering if it will get fixed if I reinstall my OST? Can’t find a way around and I’m new to programming. I really appreciate your help.

Issue:
Error: [NodeId: Terrain-Correction] Operator 'RangeDopplerGeocodingOp': Unknown element 'outputComplex'

Alexis A

**Comment by AleksandrTulenkov** [comment]
> Hi Aleksandr,
> 
> there are lots of changes, because of aded spaces, so I am not finding the issue. Can you resend Can you resend the PR without those spaces, so I can just see what actually went wrong? In addition, which SNAP version do you use? Problems with xml files are usually tied to specifics of SNAP versions. OST at the moment uses Snap version 8
> 
> Thanks, Andreas

Hi. Commit updated, SNAP ver 8, outputComplex was deleted from the last updates

**Comment by AleksandrTulenkov** [comment]
> 

Yes. As for me it works after deleting this line from all xmls. But I'm not library developer and can't answer is that a good way to solve issue

**Comment by BuddyVolly** [comment]
Dear Aleksandr, 

I really would like to help, but still in the changes I see all xml files involved. Without having to go through all those small changes, I cannot see what actually is your problem. What I will do is to close this PR without accepting it. Please do open anew one with ONLY the change you want to do.

Thanks for your understanding,
BV

**Pull request closed without merging**
